import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="bg-white shadow flex gap-4 p-3">
            <Link href="/" className="hover:text-blue-600 font-medium">
              Home
            </Link>
            <Link
              href="/GsapStagger"
              className="hover:text-blue-600 font-medium"
            >
              Gsap Stagger
            </Link>
            <Link href="/contact" className="hover:text-blue-600 font-medium">
              Contact
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
